### ISSUE TITLE
DOSbox ECE Fluidsynth patch issue

### ISSUE THREAD

**Issue by jxhicks** [theMK2k/MetropolisLauncher#25] opened 2017-11-29 15:32 UTC
There appears to be a problem with the Fluidsynth gain setting for DOSbox ECE.  It seems that when using the default setting of 0.600 it somehow gets reset to a null value in the .conf file resulting in no audible sound from MIDI in games.  Setting it to something else, like 0.610 results it it working as expected.  I do not have this problem with DOSbox ECE on it's own.

**Comment by theMK2k** [comment] 2017-11-29 18:01
Bug confirmed.

Default values result in the following .conf entries:

fluid.samplerate=48000
**fluid.gain=**
fluid.polyphony=256
fluid.cores=default
fluid.periods=8
fluid.periodsize=512
fluid.reverb=yes
**fluid.reverb,roomsize=**
**fluid.reverb.damping=**
**fluid.reverb.width=**
**fluid.reverb.level=**
fluid.chorus=yes
fluid.chorus.number=3
**fluid.chorus.level=**
**fluid.chorus.speed=**
**fluid.chorus.depth=**
fluid.chorus.type=0

this is not intended and will be fixed.

**Comment by jxhicks** [comment] 2017-11-29 18:06
Oh wow, I didn't even notice all the other settings being left blank too.  Thanks for looking into it.

**Comment by theMK2k** [comment] 2017-11-29 18:56
Found the culprit, output is now:

fluid.samplerate=48000
fluid.gain=.6
fluid.polyphony=256
fluid.cores=default
fluid.periods=8
fluid.periodsize=512
fluid.reverb=yes
fluid.reverb,roomsize=.61
fluid.reverb.damping=.23
fluid.reverb.width=.76
fluid.reverb.level=.57
fluid.chorus=yes
fluid.chorus.number=3
fluid.chorus.level=1.2
fluid.chorus.speed=.3
fluid.chorus.depth=8
fluid.chorus.type=0

which looks way better :)

**Comment by jxhicks** [comment] 2017-11-29 18:58
That's great, thanks so much.

**Comment by theMK2k** [comment] 2017-11-29 19:04
The bug should be fixed, please download the attached update and test :)

[Metropolis_Launcher_1.1.1b_fluidsynth.zip](https://github.com/theMK2k/MetropolisLauncher/files/1515143/Metropolis_Launcher_1.1.1b_fluidsynth.zip)

**Comment by jxhicks** [comment] 2017-11-29 19:28
Just tested it and it looks to be working properly now.  Thanks again.

**Closed as completed** 2017-11-29 19:53 UTC
Labels: bug
